import type { Structure } from "./analyse";
import { ARENA_CELLS, ARENA_WEIGHT, BOSS_WEIGHT, HIT_RATE, DAMAGE_PER_AMMO } from "./metrics";
import { checkTargets, LEGACY_PROBLEMS, OLD_CRITICAL, REBUILT, TARGETS } from "./targets";

/**
 * `docs/level-structure.md`: every level's structure in one table, the fights, the hard failures each level is
 * waived and why, and the targets a rebuilt level is held to. Written by `scripts/level-structure.ts`;
 * `tests/world/structureLevels.test.ts` fails if the file is not what this prints.
 */

export interface Row { index: number; name: string; s: Structure }

const pct = (f: number): string => `${Math.round(f * 100)}%`;
const bar = (rows: string[][]): string[] => rows.map((r) => `| ${r.join(" | ")} |`);

export function structureMarkdown(rows: readonly Row[]): string {
  const out: string[] = [
    "# Level structure",
    "",
    "Generated by `npx vite-node scripts/level-structure.ts` — do not edit by hand. What each level *is*, as a graph and a route,",
    "measured by `src/world/structure/` (deeper-levels plan, Task 2). `tests/world/structureLevels.test.ts` runs every level through the",
    "same code as hard validation and fails if this file is out of date.",
    "",
    "## How it is measured",
    "",
    "- **Walking.** Four-way, cell to cell; a grounded player cannot step up more than 1.2 (`Player.ts`), going down is free, so a drop is one-way. `D` opens with the key",
    "  (one key opens every `D`), `+` always, `S` only where a question allows secrets; the way through a level never needs one. Decor masses and the piano are walls.",
    "- **Critical path** = steps (cells entered) from `P` through every goal in order, finding the key on the way if a locked door is in the way: the exit pad `X`; or a boss",
    "  from `QZNHV` and then the first open cell of the exit list (`Death.ts`'s `openExit`); or, on the finale, the boss `G`.",
    "- **Rooms** are connected sets of at least 6 cells lying in 2x2 open blocks (a corridor has none); everything else open is a **passage**. **Loops** are the independent cycles of the graph of",
    "  rooms and passages (`E - V + C`), secret doors left out. **Branches** are regions with three or more neighbours; **dead ends** are regions with one that are neither the start nor the goal.",
    "- **Heights** are the distinct floor heights; **transitions** the boundaries between constant-height patches (a stair of n steps has n).",
    "- **Checkpoint** *fraction* is where the nearest cell of the critical path stands, 0 at the spawn, 1 at the exit; *forced* means every way through the level passes within the marker's reach (2.6).",
    `- **Fights.** For each region with enemies: their hit points (bosses and anything of 600 or more apart), and what ammunition has been findable by the time the player is there — the pickups nearer the spawn than the region, those inside it, and the 60 bullets the player starts with —`,
    `  in *damage on paper* (the first weapon that fires each kind, pellets and all) at ${pct(HIT_RATE)} accuracy: bullets ${DAMAGE_PER_AMMO.bullets}, shells ${DAMAGE_PER_AMMO.shells}, slugs ${DAMAGE_PER_AMMO.slugs}, crosses ${DAMAGE_PER_AMMO.crosses}, nails ${DAMAGE_PER_AMMO.nails}, souls ${DAMAGE_PER_AMMO.souls} per unit. What enemies drop is not counted.`,
    `  An **arena** is a room of ${ARENA_CELLS}+ cells holding ${ARENA_WEIGHT}+ of enemy weight (a boss weighs ${BOSS_WEIGHT}).`,
    "",
    "## Every level",
    "",
    ...bar([
      ["level", "walkable", "critical path", "key", "rooms", "passages", "loops", "branches", "dead ends", "heights", "transitions", "keys / locked / doors", "secrets (pickups)", "checkpoints (path fraction)", "enemies", "arenas", "exit door"],
      ["---", "---:", "---:", "---", "---:", "---:", "---:", "---:", "---:", "---:", "---:", "---", "---", "---", "---:", "---:", "---"],
      ...rows.map(({ index, name, s }) => [
        `${index} · ${name.replace(/^LEVEL \d — /, "").replace(/^PROLOGUE — /, "prologue · ")}`, String(s.walkable), `${s.critical.length}`,
        s.critical.keyRequired ? `required, ${s.critical.detour} steps off the way` : s.keys ? "optional" : "-",
        String(s.rooms), String(s.passages), String(s.loops), String(s.branches), String(s.deadEnds), String(s.heights), String(s.transitions),
        `${s.keys} / ${s.lockedDoors} / ${s.plainDoors}`, `${s.secrets} (${s.secretRewards.join(", ") || "-"})`,
        s.checkpoints.map((c) => `${pct(c.fraction)}${c.forced ? " forced" : ""}`).join(", ") || "-",
        `${s.enemies} (${s.enemyHp} + ${s.bossHp} boss hp)`, String(s.arenas), s.exitSite,
      ]),
    ]),
    "",
    "The prologue is one open cavern (hell) and one yard (the zones of `prologue.ts`), so \"rooms\" says little there. Levels 4-6 share a critical path of exactly 44: the same building with different wallpaper",
    "(`docs/level-density.md`). Levels 3-7 have a key and a locked door but no key on the way: the door guards a side chamber, so there is no key hunt.",
    "",
    "## Fights, level by level",
    "",
    "Regions with enemies, in reading order. *ratio* is ammunition-worth over hit points (all of them, bosses included).",
    "",
  ];
  for (const { index, name, s } of rows) {
    if (!s.encounters.length) continue;
    out.push(`### ${index} · ${name.replace(/^LEVEL \d — /, "").replace(/^PROLOGUE — /, "prologue · ")}`, "",
      ...bar([
        ["region", "kind", "cells", "enemies", "hp", "boss hp", "ammo worth", "health", "armour", "ratio"],
        ["---", "---", "---:", "---:", "---:", "---:", "---:", "---:", "---:", "---:"],
        ...s.encounters.map((e) => [`x ${e.x0}-${e.x1}, z ${e.z0}-${e.z1}`, e.kind, String(e.cells), String(e.enemies), String(e.hp), String(e.bossHp), String(Math.round(e.supply)), String(e.health), String(e.armour), e.ratio.toFixed(2)]),
      ]), "");
  }
  out.push(
    "## Hard failures",
    "",
    "Every level passes the hard validation (`analyse().problems`: reachability, key before door, no softlock, everything reachable, secrets behind secret doors, the exit door sited) except for these, which the old",
    "levels already had and which a rebuilt level must not (`LEGACY_PROBLEMS`, `src/world/structure/targets.ts`):",
    "",
  );
  for (const r of rows) {
    const codes = [...new Set(r.s.problems.map((p) => p.code))].sort();
    if (!codes.length && !(LEGACY_PROBLEMS[r.index] || []).length) continue;
    out.push(`- **${r.index} · ${r.name}**`, ...r.s.problems.map((p) => `  - \`${p.code}\`: ${p.message}`));
  }
  out.push(
    "",
    "## The targets a rebuilt level is held to",
    "",
    "A level listed in `REBUILT` (`src/world/structure/targets.ts`) must meet every number below (`checkTargets`), as well as the hard validation with no waiver.",
    "",
    ...bar([
      ["target", "number", "measured today"],
      ["---", "---", "---"],
      ["critical path", `${TARGETS.pathMin}-${TARGETS.pathMax}x the old level's, and at least ${TARGETS.pathFloor} steps`, rows.filter((r) => r.index).map((r) => `${r.index}: ${r.s.critical.length}`).join(", ")],
      ["loops", `at least ${TARGETS.loops}`, rows.filter((r) => r.index).map((r) => `${r.index}: ${r.s.loops}`).join(", ")],
      ["key hunt", `a key, a locked door on the way, the key at least ${TARGETS.keyDetour} steps off it`, rows.filter((r) => r.index).map((r) => `${r.index}: ${r.s.critical.keyRequired ? r.s.critical.detour : "none"}`).join(", ")],
      ["secrets", `at least ${TARGETS.secrets}, each with at least ${TARGETS.secretRewards} pickups behind it`, rows.filter((r) => r.index).map((r) => `${r.index}: ${r.s.secrets}`).join(", ")],
      ["arena", `at least ${TARGETS.arenas}`, rows.filter((r) => r.index).map((r) => `${r.index}: ${r.s.arenas}`).join(", ")],
      ["verticality", `at least ${TARGETS.heights} floor heights and ${TARGETS.transitions} transitions`, rows.filter((r) => r.index).map((r) => `${r.index}: ${r.s.heights}/${r.s.transitions}`).join(", ")],
      ["rooms, branch points", `at least ${TARGETS.rooms} rooms, ${TARGETS.branches} branch points`, rows.filter((r) => r.index).map((r) => `${r.index}: ${r.s.rooms}/${r.s.branches}`).join(", ")],
      ["checkpoint", `one that every route passes, between ${pct(TARGETS.checkpointFrom)} and ${pct(TARGETS.checkpointTo)} of the critical path`, rows.filter((r) => r.index).map((r) => `${r.index}: ${r.s.checkpoints.some((c) => c.forced && c.fraction >= TARGETS.checkpointFrom && c.fraction <= TARGETS.checkpointTo) ? "yes" : "no"}`).join(", ")],
      ["fights", `ammunition worth at least ${TARGETS.supplyOverHp}x the rank-and-file hit points of a region; ${TARGETS.supplyOverBossHp}x all of them before a boss, with ${TARGETS.bossHealth} health and ${TARGETS.bossArmour} armour on the way`, "see the tables above"],
    ]),
    "",
    `Old critical paths (the 1x of "about twice"): ${Object.entries(OLD_CRITICAL).map(([i, n]) => `${i}: ${n}`).join(", ")}. \`REBUILT\` is ${REBUILT.length ? REBUILT.join(", ") : "empty: no level has been rebuilt yet"}.`,
    "",
    "What the levels as built miss, by the targets (a rebuilt level starts from none of these):",
    "",
  );
  for (const r of rows) if (r.index) out.push(`- ${r.index}: ${checkTargets(r.index, r.s).length} unmet`);
  out.push("");
  return out.join("\n");
}
