// Measures every sound in the game and writes docs/sound-levels.md.
//
//   node scripts/sound-levels.mjs            measure, write the doc
//   node scripts/sound-levels.mjs --apply    also move every trim in
//                                            src/audio/Levels.ts to the
//                                            suggested one (run it again after:
//                                            the compressors are not linear,
//                                            so it takes two or three passes)
//
// Player feedback round 2, Task 2. The measuring itself is in the sound
// board (src/soundboard/measure.ts): it needs a real OfflineAudioContext,
// which Node does not have. So this starts the Vite dev server, opens the
// board in a headless Chrome or Edge (CHROME=path overrides the search),
// drives it over the DevTools protocol with Node's own WebSocket — no new
// dependency — and turns what `soundboard.levels()` returns into markdown.

import { spawn } from "node:child_process";
import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { createServer } from "vite";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const APPLY = process.argv.includes("--apply");
const DOC = join(ROOT, "docs", "sound-levels.md");
const LEVELS = join(ROOT, "src", "audio", "Levels.ts");

function findBrowser() {
  const candidates = [
    process.env.CHROME,
    "C:/Program Files/Google/Chrome/Application/chrome.exe",
    "C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe",
    "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
    "/usr/bin/google-chrome", "/usr/bin/chromium", "/usr/bin/chromium-browser",
  ].filter(Boolean);
  const found = candidates.find((p) => existsSync(p));
  if (!found) throw new Error("no Chrome/Edge found; set CHROME=/path/to/chrome");
  return found;
}

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

async function devtools(browser, url) {
  const profile = mkdtempSync(join(tmpdir(), "sound-levels-"));
  const proc = spawn(browser, [
    "--headless=new", "--remote-debugging-port=0", `--user-data-dir=${profile}`,
    "--no-first-run", "--no-default-browser-check", "--autoplay-policy=no-user-gesture-required", "about:blank",
  ], { stdio: "ignore" });
  const portFile = join(profile, "DevToolsActivePort");
  for (let i = 0; i < 100 && !existsSync(portFile); i++) await sleep(100);
  if (!existsSync(portFile)) throw new Error("the browser did not open a DevTools port");
  await sleep(200);
  const port = readFileSync(portFile, "utf8").split("\n")[0].trim();
  const pages = await (await fetch(`http://127.0.0.1:${port}/json/list`)).json();
  const page = pages.find((p) => p.type === "page");
  const ws = new WebSocket(page.webSocketDebuggerUrl);
  await new Promise((res, rej) => { ws.onopen = res; ws.onerror = rej; });
  let id = 0;
  const waiting = new Map();
  ws.onmessage = (m) => {
    const msg = JSON.parse(m.data);
    if (msg.id && waiting.has(msg.id)) { waiting.get(msg.id)(msg); waiting.delete(msg.id); }
  };
  const send = (method, params = {}) => new Promise((res) => { const n = ++id; waiting.set(n, res); ws.send(JSON.stringify({ id: n, method, params })); });
  async function evaluate(expression) {
    const r = await send("Runtime.evaluate", { expression, awaitPromise: true, returnByValue: true });
    if (r.result?.exceptionDetails) throw new Error(JSON.stringify(r.result.exceptionDetails));
    return r.result?.result?.value;
  }
  await send("Page.navigate", { url });
  for (let i = 0; i < 200 && !(await evaluate("typeof window.soundboard === 'object'")); i++) await sleep(100);
  const version = (await send("Browser.getVersion")).result?.product;
  const close = () => { ws.close(); proc.kill(); try { rmSync(profile, { recursive: true, force: true }); } catch { /* the browser may still hold it */ } };
  return { evaluate, version, close };
}

const f1 = (x) => (Number.isFinite(x) ? x.toFixed(1) : "−∞");
const signed = (x) => (x > 0 ? `+${f1(x)}` : f1(x));

function markdown(r, version) {
  const L = [];
  L.push("# Sound levels");
  L.push("");
  L.push("<!-- generated by `node scripts/sound-levels.mjs` — do not edit by hand; re-run it. -->");
  L.push("");
  L.push("This file is generated by `node scripts/sound-levels.mjs`, which renders every sound on the sound board offline (a real `OfflineAudioContext`, in " + version + ", driven headless) and measures it. Player feedback round 2, Task 2: loudness is a design decision. The trims below are the ones `src/audio/Levels.ts` plays; `tests/audio/levels.test.ts` fails if the two disagree.");
  L.push("");
  L.push("## How it is measured");
  L.push("");
  L.push("- **Before** is the game as it was before Task 2: the board's *Old mix* (`src/soundboard/previous/mix.ts` — the reference's graph: one master gain, a 340 ms feedback-delay echo with no dry path, no compressor, no limiter, no trims).");
  L.push("- **After** is the game now: the new mix (`src/audio/Mix.ts`) in the stone hall (the room of the dungeon, church and necropolis), with every trim applied.");
  L.push("- Both at master volume **1** (the slider's top; the default is 0.5, which is 6 dB below every figure here), mono, 48 kHz, starting 0.5 s into the render (Chrome's compressor is not transparent in the first frames of a render; see `src/soundboard/offline.ts`). Timer-scheduled parts of a sound (a death cry's gurgle, the heartbeat's second beat, a boss roar's second growl, the casing clink) are in the render.");
  L.push("- **LK** is LK-fast: K-weighted loudness (ITU-R BS.1770 filter), the loudest 125 ms window, in LKFS — the figure the targets are set in. **Peak** is sample peak, dBFS. **RMS** is over the stretch within 60 dB of the peak, dBFS — for *after* that includes the room's tail, so it reads lower than *before* for a sound of the same loudness.");
  L.push("");
  L.push("## The master chain");
  L.push("");
  const c = r.chain;
  L.push(`- Glue compressor: threshold ${c.glue.threshold} dBFS, knee ${c.glue.knee} dB, ratio ${c.glue.ratio}:1, attack ${c.glue.attack * 1000} ms, release ${c.glue.release * 1000} ms.`);
  L.push(`- Limiter: threshold ${c.limit.threshold} dBFS, knee ${c.limit.knee} dB, ratio ${c.limit.ratio}:1, attack ${c.limit.attack * 1000} ms, release ${c.limit.release * 1000} ms.`);
  L.push(`- Soft clip: identity to ${c.clip.knee}, tanh shoulder above, never reaching ${c.clip.ceiling} (${f1(20 * Math.log10(c.clip.ceiling))} dBFS); not oversampled. Then the master volume, clamped to 0-1.`);
  L.push(`- Reverb sends: ${c.drySend} for a sound through \`masterBus()\`, ${c.echoSend} through \`echoBus()\` (what used to be the echo), times the sound's own \`room\` factor.`);
  L.push("");
  L.push("### The worst case");
  L.push("");
  L.push("| Everything at once, at volume 1 | Peak before | Clipped samples before | Peak after | Clipped samples after |");
  L.push("|---|---|---|---|---|");
  for (const w of r.worst) L.push(`| ${w.name} | ${signed(w.oldPeakDb)} dBFS | ${w.oldClipped} | ${signed(w.newPeakDb)} dBFS | ${w.newClipped} |`);
  L.push("");
  L.push("## The rooms");
  L.push("");
  L.push("| Room | IR length | RT60 | Pre-delay | Return | Shotgun: the room's tail after the dry sound ends, vs the dry sound | IR build time |");
  L.push("|---|---|---|---|---|---|---|");
  for (const m of r.rooms) L.push(`| ${m.label} | ${m.seconds} s stereo | ${m.rt60} s | ${Math.round(m.predelay * 1000)} ms | ${m.wet} | ${signed(m.reverbDb)} dB | ${m.buildMs.toFixed(1)} ms |`);
  L.push("");
  L.push("### Render cost");
  L.push("");
  L.push("Offline render time of 20 s of the drone bed plus a boss roar, per second of audio. Offline rendering runs as fast as it can on one thread, so this is the cost of the graph, not a real-time CPU figure — but the difference between the rows is what the room and the chain cost.");
  L.push("");
  L.push("| Mix | ms per second of audio |");
  L.push("|---|---|");
  for (const x of r.cost) L.push(`| ${x.what} | ${x.msPerSecond.toFixed(2)} |`);
  L.push("");
  L.push("## Targets and trims");
  L.push("");
  L.push("Weapons loudest, then explosions, monsters, impacts, footsteps, UI quietest (the owner's order); world events sit with the monsters, weapon foley between impacts and footsteps, ambience just above the UI. A sound with several rows (a pain cry at six pitches, a footstep walking and running) has one trim, set from the mean of its rows, so its variants keep their relation. The automatic weapons (combat rifle, tommy gun, nail cannon) are levelled by one second of fire at their own rate — \"(burst)\" — because that is how a player hears them.");
  L.push("");
  L.push("A trim never pushes one sound on its own past " + r.peakCeiling + " dBFS peak, or above +" + r.maxTrim + " dB: the limiter is for sounds piling up, not for flattening one. A sound that cannot reach its target under that ceiling is **peak-bound** — its energy is all in a few milliseconds, and what it needs is a longer body (sound design, Tasks 3-5), not more level.");
  L.push("");
  L.push("| Entry | Category | Trim (dB) | Target LK | LK after | Peak after | Error | Held by | Suggested trim |");
  L.push("|---|---|---|---|---|---|---|---|---|");
  for (const e of r.entries) L.push(`| \`${e.name}\` | ${e.category} | ${e.trim} | ${e.target} | ${f1(e.lk)}${e.burst ? " (burst)" : ""} | ${f1(e.peak)} | ${signed(e.error)} | ${e.bound === "peak" ? "peak-bound" : e.bound === "cap" ? "trim cap" : "—"} | ${e.suggested} |`);
  L.push("");
  L.push("## Every sound, before and after");
  L.push("");
  L.push("| Sound | Entry | Peak before | Peak after | RMS before | RMS after | LK before | LK after | Target | Change |");
  L.push("|---|---|---|---|---|---|---|---|---|---|");
  for (const x of r.rows) {
    L.push(`| ${x.name} | ${x.entry ? `\`${x.entry}\`` : x.category} | ${f1(x.before.peakDb)} | ${f1(x.after.peakDb)} | ${f1(x.before.rmsDb)} | ${f1(x.after.rmsDb)} | ${f1(x.before.lk)} | ${f1(x.after.lk)} | ${x.target ?? "—"} | ${signed(x.after.lk - x.before.lk)} |`);
  }
  L.push("");
  return L.join("\n");
}

function applyTrims(entries) {
  let src = readFileSync(LEVELS, "utf8");
  let changed = 0;
  for (const e of entries) {
    const key = /^[A-Za-z_$][\w$]*$/.test(e.name) ? e.name : `"${e.name}"`;
    const re = new RegExp(`^(  ${key.replace(/[.$]/g, "\\$&")}: \\{ category: "\\w+", trim: )(-?\\d+(?:\\.\\d+)?)([ ,])`, "m");
    if (!re.test(src)) throw new Error(`could not find ${e.name}'s line in Levels.ts`);
    src = src.replace(re, (_m, a, old, b) => { if (Number(old) !== e.suggested) changed++; return `${a}${e.suggested}${b}`; });
  }
  writeFileSync(LEVELS, src);
  return changed;
}

const server = await createServer({ root: ROOT, logLevel: "error", server: { port: 5199, strictPort: false } });
await server.listen();
const url = `${server.resolvedUrls.local[0]}soundboard.html`;
const browser = await devtools(findBrowser(), url);
try {
  process.stdout.write(`measuring in ${browser.version} … `);
  const report = await browser.evaluate("soundboard.levels()");
  if (!report) throw new Error("soundboard.levels() returned nothing");
  console.log(`${report.rows.length} sounds`);
  writeFileSync(DOC, markdown(report, browser.version));
  console.log(`wrote ${DOC}`);
  const worst = Math.max(...report.entries.map((e) => Math.abs(e.error)));
  console.log(`largest distance from target: ${worst.toFixed(1)} dB; worst-case peaks: ${report.worst.map((w) => w.newPeakDb.toFixed(2)).join(", ")} dBFS`);
  if (APPLY) console.log(`--apply: ${applyTrims(report.entries)} trims changed in src/audio/Levels.ts — run again to measure them`);
} finally {
  browser.close();
  await server.close();
}
