/**
 * Weapon pixel-art rows, slots 4-7: BMG SNIPER, HOLY CROSS LAUNCHER, NAIL
 * CANNON, SOUL REAPER. See src/render/viewmodel/pixels/weapons0.ts's doc
 * comment for the extraction method, split rationale and the "every
 * character is art" rule - identical here.
 *
 * Copied verbatim from reference/sonsurum.html lines 2418-2508.
 */
export const WEAPONS_4_7 = [
  { // 4: BMG SNIPER
    idle: [[
      "      .aac.          ","      .Lbc.          ","      .Lbc.          ","      .Lbc.          ",
      "      .Lbc.          ","    .eePccPee.       ","   .ePUVQVUPe.       ","   .ePVQQQVPe.       ",
      "   .ePUVQVUPe.       ","  .eccccccccb.       ","   .LLNbccdeeg.      ","   .LNbc.deeb.       ",
      "  .GLNbccddeegJ.     ","  GJKLNbccdeegKJG    ","   .JKwxyzZeKJ.      ","    .wxyzze.         ",
      "    .wxyzze.         ","    .wwxyzz.         ","     .wxzz.          ","     .wwz.           ",
      "      .wz.           ",
    ]],
    fire: [[
      "      .aac.          ","      .Lbc.          ","      .Lbc.          ","      .Lbc.          ",
      "      .Lbc.          ","    .eePccPee.       ","   .ePUVQVUPe.       ","   .ePVQQQVPe.       ",
      "   .ePUVQVUPe.       ","  .eccccccccb.       ","   .LLNbccdeeg.      ","   .LNbc.deeb.       ",
      "  .GLNbccddeegJ.     ","  GJKLNbccdeegKJG    ","   .JKwxyzZeKJ.      ","    .wxyzze.         ",
      "    .wxyzze.         ","    .wwxyzz.         ","     .wxzz.          ","     .wwz.           ",
      "      .wz.           ",
    ], [
      "      .aac.          ","      .Lbc.          ","      .Lbc.          ","      .Lbc.          ",
      "      .Lbc.          ","    .eePccPee.       ","   .ePUVQVUPe.       ","   .ePVQQQVPe.       ",
      "   .ePUVQVUPe.       ","  .eccccccccb.       ","   .LLNbccdeeg.      ","   .LNbc.deeb.       ",
      "  .GLNbccddeegJ.     ","  GJKLNbccdeegKJG    ","   .JKwxyzZeKJ.      ","    .wxyzze.         ",
      "    .wxyzze.         ","    .wwxyzz.         ","     .wxzz.          ","     .wwz.           ",
      "      .wz.           ",
    ]],
    reload: [[
      "      .aac.          ","      .Lbc.          ","      .Lbc.          ","      .Lbc.          ",
      "      .Lbc.          ","    .eePccPee.       ","   .ePUVQVUPe.       ","   .ePVQQQVPe.       ",
      "   .ePUVQVUPe.       ","  .eccccccccb.       ","   .LLNbccdeeg.      ","   .LNbc.deeb.       ",
      "  .GLNbccddeegJ.     ","  GJKLNbccdeegKJG    ","   .JKwxyzZeKJ.      ","    .wxyzze.         ",
      "    .wxyzze.         ","    .wwxyzz.         ","     .wxzz.          ","     .wwz.           ",
      "      .wz.           ",
    ], [
      "      .aac.          ","      .Lbc.          ","      .Lbc.          ","    .eePccPee.       ",
      "   .ePUVQVUPe.       ","   .ePVQQQVPe.       ","  .eccccccccb.       ","   .LLNbccdeeg.      ",
      "  .GLNbccddeegJ.     ","  GJKLNbccdeegKJG    ","   .JKwxyzZeKJ.      ","    ..eeoee..        ",
      "    .eoooooe.        ","    .eoooooe.        ","   GK.eooooe.KG      ","    K.eoooe.K        ",
      "     .eooe.          ","      .KK.           ","                     ","                     ",
      "                     ",
    ], [
      "      .aac.          ","      .Lbc.          ","      .Lbc.          ","      .Lbc.          ",
      "      .Lbc.          ","    .eePccPee.       ","   .ePUVQVUPe.       ","   .ePVQQQVPe.       ",
      "   .ePUVQVUPe.       ","  .eccccccccb.       ","   .LLNbccdeeg.      ","   .LNbc.deeb.       ",
      "  .GLNbccddeegJ.     ","  GJKLNbccdeegKJG    ","   .JKwxyzZeKJ.      ","    .wxyzze.         ",
      "    .wxyzze.         ","    .wwxyzz.         ","     .wxzz.          ","     .wwz.           ",
      "      .wz.           ",
    ]],
  },
  { // 5: HOLY CROSS LAUNCHER
    idle: [[
      "      .mmnn.         ","     .mBnnBm.        ","     .mB..Bm.        ","     .mn.Cnm.        ",
      "     .mnCCnm.        ","    .mmnoonmm.       ","   .mBnooooBnm.      ","  .mnooooooonm.      ",
      "  .mnoo.CC.oonm.     ","  .mnoCCWWCConm.     ","  .mnoo.CC.oonm.     ","  .GmnooooooonmJ.    ",
      "  GJKmmnoooonmKJG    ","  .JKwxyzZZyxwKJ.    ","    .wxyzZZyxw.      ","    .wxy.zzyxw.      ",
      "    .wwx.zzyxw.      ","     .wx.zzxw.       ","     .wwzzzzw.       ","      .wwzzw.        ",
      "       .wwz.         ",
    ]],
    fire: [[
      "      .mmnn.         ","     .mBnnBm.        ","     .mB..Bm.        ","     .mn.Cnm.        ",
      "     .mnCCnm.        ","    .mmnoonmm.       ","   .mBnooooBnm.      ","  .mnooooooonm.      ",
      "  .mnoo.CC.oonm.     ","  .mnoCCWWCConm.     ","  .mnoo.CC.oonm.     ","  .GmnooooooonmJ.    ",
      "  GJKmmnoooonmKJG    ","  .JKwxyzZZyxwKJ.    ","    .wxyzZZyxw.      ","    .wxy.zzyxw.      ",
      "    .wwx.zzyxw.      ","     .wx.zzxw.       ","     .wwzzzzw.       ","      .wwzzw.        ",
      "       .wwz.         ",
    ], [
      "      .mmnn.         ","     .mBnnBm.        ","     .mB..Bm.        ","     .mn.Cnm.        ",
      "     .mnCCnm.        ","    .mmnoonmm.       ","   .mBnooooBnm.      ","  .mnooooooonm.      ",
      "  .mnoo.CC.oonm.     ","  .mnoCCWWCConm.     ","  .mnoo.CC.oonm.     ","  .GmnooooooonmJ.    ",
      "  GJKmmnoooonmKJG    ","  .JKwxyzZZyxwKJ.    ","    .wxyzZZyxw.      ","    .wxy.zzyxw.      ",
      "    .wwx.zzyxw.      ","     .wx.zzxw.       ","     .wwzzzzw.       ","      .wwzzw.        ",
      "       .wwz.         ",
    ]],
    reload: [[
      "      .mmnn.         ","     .mBnnBm.        ","     .mB..Bm.        ","     .mn.Cnm.        ",
      "     .mnCCnm.        ","    .mmnoonmm.       ","   .mBnooooBnm.      ","  .mnooooooonm.      ",
      "  .mnoo.CC.oonm.     ","  .mnoCCWWCConm.     ","  .mnoo.CC.oonm.     ","  .GmnooooooonmJ.    ",
      "  GJKmmnoooonmKJG    ","  .JKwxyzZZyxwKJ.    ","    .wxyzZZyxw.      ","    .wxy.zzyxw.      ",
      "    .wwx.zzyxw.      ","     .wx.zzxw.       ","     .wwzzzzw.       ","      .wwzzw.        ",
      "       .wwz.         ",
    ], [
      "      .mmnn.         ","     .mBnnBm.        ","     .mnoonm.        ","    .mmnoonmm.       ",
      "   .mBnooooBnm.      ","  .mnooooooonm.      ","  .GmnooooooonmJ.    ","  GJKmmnoooonmKJG    ",
      "  .JKwxyzZZyxwKJ.    ","    .wxyzZZyxw.      ","     CCWWC..         ","    CWWWWC..         ",
      "   C.CCWC.JK         ","    CCWCC.K          ","    .CCCC.           ","     CCC.            ",
      "      C.             ","                     ","                     ","                     ",
      "                     ",
    ], [
      "      .mmnn.         ","     .mBnnBm.        ","     .mB..Bm.        ","     .mn.Cnm.        ",
      "     .mnCCnm.        ","    .mmnoonmm.       ","   .mBnooooBnm.      ","  .mnooooooonm.      ",
      "  .mnoo.CC.oonm.     ","  .mnoCCWWCConm.     ","  .mnoo.CC.oonm.     ","  .GmnooooooonmJ.    ",
      "  GJKmmnoooonmKJG    ","  .JKwxyzZZyxwKJ.    ","    .wxyzZZyxw.      ","    .wxy.zzyxw.      ",
      "    .wwx.zzyxw.      ","     .wx.zzxw.       ","     .wwzzzzw.       ","      .wwzzw.        ",
      "       .wwz.         ",
    ]],
  },
  { // 6: NAIL CANNON
    idle: [[
      "  .a..a..a..a.       ","  .b..b..b..b.       ","  .b..b..b..b.       ","  .baabaabaab.       ",
      "  .bccbccbccb.       ","  .bcdcdcdccb.       ","  .ddddddddde.       ","  .dccccccddee.      ",
      " .Gddcccccddeeg.     ","  GJKddccddeegKJG    ","  .JKLddcddeegKJ.    ","  .LLddccddee.       ",
      "  .Ldd.PP.dee.       ","  .Gdd.PP.dee.J.     ","  GJKwxyzZZyxzKJG    ","  .JKwxxyyzzxzJ.     ",
      "    .wwxxyyzzw.      ","     .wwxxyzw.       ","      .wwxyw.        ","       .wwz.         ",
      "        .w.          ",
    ]],
    fire: [[
      "  .a..a..a..a.       ","  .b..b..b..b.       ","  .b..b..b..b.       ","  .baabaabaab.       ",
      "  .bccbccbccb.       ","  .bcdcdcdccb.       ","  .ddddddddde.       ","  .dccccccddee.      ",
      " .Gddcccccddeeg.     ","  GJKddccddeegKJG    ","  .JKLddcddeegKJ.    ","  .LLddccddee.       ",
      "  .Ldd.PP.dee.       ","  .Gdd.PP.dee.J.     ","  GJKwxyzZZyxzKJG    ","  .JKwxxyyzzxzJ.     ",
      "    .wwxxyyzzw.      ","     .wwxxyzw.       ","      .wwxyw.        ","       .wwz.         ",
      "        .w.          ",
    ], [
      "  .a..a..a..a.       ","  .b..b..b..b.       ","  .b..b..b..b.       ","  .baabaabaab.       ",
      "  .bccbccbccb.       ","  .bcdcdcdccb.       ","  .ddddddddde.       ","  .dccccccddee.      ",
      " .Gddcccccddeeg.     ","  GJKddccddeegKJG    ","  .JKLddcddeegKJ.    ","  .LLddccddee.       ",
      "  .Ldd.PP.dee.       ","  .Gdd.PP.dee.J.     ","  GJKwxyzZZyxzKJG    ","  .JKwxxyyzzxzJ.     ",
      "    .wwxxyyzzw.      ","     .wwxxyzw.       ","      .wwxyw.        ","       .wwz.         ",
      "        .w.          ",
    ], [
      "  .a..a..a..a.       ","  .b..b..b..b.       ","  .b..b..b..b.       ","  .baabaabaab.       ",
      "  .bccbccbccb.       ","  .bcdcdcdccb.       ","  .ddddddddde.       ","  .dccccccddee.      ",
      " .Gddcccccddeeg.     ","  GJKddccddeegKJG    ","  .JKLddcddeegKJ.    ","  .LLddccddee.       ",
      "  .Ldd.PP.dee.       ","  .Gdd.PP.dee.J.     ","  GJKwxyzZZyxzKJG    ","  .JKwxxyyzzxzJ.     ",
      "    .wwxxyyzzw.      ","     .wwxxyzw.       ","      .wwxyw.        ","       .wwz.         ",
      "        .w.          ",
    ]],
    reload: [[
      "  .a..a..a..a.       ","  .b..b..b..b.       ","  .b..b..b..b.       ","  .baabaabaab.       ",
      "  .bccbccbccb.       ","  .bcdcdcdccb.       ","  .ddddddddde.       ","  .dccccccddee.      ",
      " .Gddcccccddeeg.     ","  GJKddccddeegKJG    ","  .JKLddcddeegKJ.    ","  .LLddccddee.       ",
      "  .Ldd.PP.dee.       ","  .Gdd.PP.dee.J.     ","  GJKwxyzZZyxzKJG    ","  .JKwxxyyzzxzJ.     ",
      "    .wwxxyyzzw.      ","     .wwxxyzw.       ","      .wwxyw.        ","       .wwz.         ",
      "        .w.          ",
    ], [
      "  .a..a..a..a.       ","  .b..b..b..b.       ","  .baabaabaab.       ","  .bccbccbccb.       ",
      "  .ddddddddde.       ","  .dccccccddee.      "," .Gddcccccddeeg.     ","  GJKddccddeegKJG    ",
      "  .JKwxyzZZyxzKJ.    ","    .wwxxyyzzw.      ","    .HHHHHHH..       ","   .HnHnHnHn..       ",
      "   .HHHHHHHH.        ","   GK.HHHHH.KG       ","    K.HHH.K          ","     ....            ",
      "                     ","                     ","                     ","                     ",
      "                     ",
    ], [
      "  .a..a..a..a.       ","  .b..b..b..b.       ","  .b..b..b..b.       ","  .baabaabaab.       ",
      "  .bccbccbccb.       ","  .bcdcdcdccb.       ","  .ddddddddde.       ","  .dccccccddee.      ",
      " .Gddcccccddeeg.     ","  GJKddccddeegKJG    ","  .JKLddcddeegKJ.    ","  .LLddccddee.       ",
      "  .Ldd.PP.dee.       ","  .Gdd.PP.dee.J.     ","  GJKwxyzZZyxzKJG    ","  .JKwxxyyzzxzJ.     ",
      "    .wwxxyyzzw.      ","     .wwxxyzw.       ","      .wwxyw.        ","       .wwz.         ",
      "        .w.          ",
    ]],
  },
  { // 7: SOUL REAPER
    idle: [[
      "      .EEEE.         ","    .EHHHHHHE.       ","   .EH.0jj0.HE.      ","   .H.0jWWj0.H.      ",
      "  .EH.jWGGWj.HE.     ","  .EHjWG00GWjHE.     ","  .EH.jWGGWj.HE.     ","   .H.0jWWj0.H.      ",
      "   .EH.0jj0.HE.      ","  .GEHHHHHHHHEgJ.    ","  GJKEEHHHHHEEKJG    ","  .JKaEHHHHEaKJ.     ",
      "   .LaaEHHEaaL.      ","  .LLaa.PP.aaL.      ","  GJKwxyzZZyxzKJG    ","  .JKwxxyyzzxzJ.     ",
      "    .wwxxyyzzw.      ","     .wwxxyzw.       ","      .wwxyw.        ","       .wwz.         ",
      "        .w.          ",
    ]],
    fire: [[
      "      .EEEE.         ","    .EHHHHHHE.       ","   .EH.0jj0.HE.      ","   .H.0jWWj0.H.      ",
      "  .EH.jWGGWj.HE.     ","  .EHjWG00GWjHE.     ","  .EH.jWGGWj.HE.     ","   .H.0jWWj0.H.      ",
      "   .EH.0jj0.HE.      ","  .GEHHHHHHHHEgJ.    ","  GJKEEHHHHHEEKJG    ","  .JKaEHHHHEaKJ.     ",
      "   .LaaEHHEaaL.      ","  .LLaa.PP.aaL.      ","  GJKwxyzZZyxzKJG    ","  .JKwxxyyzzxzJ.     ",
      "    .wwxxyyzzw.      ","     .wwxxyzw.       ","      .wwxyw.        ","       .wwz.         ",
      "        .w.          ",
    ], [
      "      .EEEE.         ","    .EHHHHHHE.       ","   .EH.0jj0.HE.      ","   .H.0jWWj0.H.      ",
      "  .EH.jWGGWj.HE.     ","  .EHjWG00GWjHE.     ","  .EH.jWGGWj.HE.     ","   .H.0jWWj0.H.      ",
      "   .EH.0jj0.HE.      ","  .GEHHHHHHHHEgJ.    ","  GJKEEHHHHHEEKJG    ","  .JKaEHHHHEaKJ.     ",
      "   .LaaEHHEaaL.      ","  .LLaa.PP.aaL.      ","  GJKwxyzZZyxzKJG    ","  .JKwxxyyzzxzJ.     ",
      "    .wwxxyyzzw.      ","     .wwxxyzw.       ","      .wwxyw.        ","       .wwz.         ",
      "        .w.          ",
    ], [
      "      .EEEE.         ","    .EHHHHHHE.       ","   .EH.0jj0.HE.      ","   .H.0jWWj0.H.      ",
      "  .EH.jWGGWj.HE.     ","  .EHjWG00GWjHE.     ","  .EH.jWGGWj.HE.     ","   .H.0jWWj0.H.      ",
      "   .EH.0jj0.HE.      ","  .GEHHHHHHHHEgJ.    ","  GJKEEHHHHHEEKJG    ","  .JKaEHHHHEaKJ.     ",
      "   .LaaEHHEaaL.      ","  .LLaa.PP.aaL.      ","  GJKwxyzZZyxzKJG    ","  .JKwxxyyzzxzJ.     ",
      "    .wwxxyyzzw.      ","     .wwxxyzw.       ","      .wwxyw.        ","       .wwz.         ",
      "        .w.          ",
    ]],
    reload: [[
      "      .EEEE.         ","    .EHHHHHHE.       ","   .EH.0jj0.HE.      ","   .H.0jWWj0.H.      ",
      "  .EH.jWGGWj.HE.     ","  .EHjWG00GWjHE.     ","  .EH.jWGGWj.HE.     ","   .H.0jWWj0.H.      ",
      "   .EH.0jj0.HE.      ","  .GEHHHHHHHHEgJ.    ","  GJKEEHHHHHEEKJG    ","  .JKaEHHHHEaKJ.     ",
      "   .LaaEHHEaaL.      ","  .LLaa.PP.aaL.      ","  GJKwxyzZZyxzKJG    ","  .JKwxxyyzzxzJ.     ",
      "    .wwxxyyzzw.      ","     .wwxxyzw.       ","      .wwxyw.        ","       .wwz.         ",
      "        .w.          ",
    ], [
      "      .EEEE.         ","    .EHHHHHHE.       ","   .EH0jjjj0HE.      ","  .EHjWGGGGWjHE.     ",
      "  .EHjWG00GWjHE.     ","  .GEHHHHHHHHEgJ.    ","  GJKEEHHHHHEEKJG    ","  .JKaEHHHHEaKJ.     ",
      "   .LaaEHHEaaL.      ","  GJKwxyzZZyxzKJG    ","    .jj00jj..        ","   .j0GGGG0j.        ",
      "   .0GGGGGG0.        ","   GK.0GG0.KG        ","    K.00.K           ","     ....            ",
      "                     ","                     ","                     ","                     ",
      "                     ",
    ], [
      "      .EEEE.         ","    .EHHHHHHE.       ","   .EH.0jj0.HE.      ","   .H.0jWWj0.H.      ",
      "  .EH.jWGGWj.HE.     ","  .EHjWG00GWjHE.     ","  .EH.jWGGWj.HE.     ","   .H.0jWWj0.H.      ",
      "   .EH.0jj0.HE.      ","  .GEHHHHHHHHEgJ.    ","  GJKEEHHHHHEEKJG    ","  .JKaEHHHHEaKJ.     ",
      "   .LaaEHHEaaL.      ","  .LLaa.PP.aaL.      ","  GJKwxyzZZyxzKJG    ","  .JKwxxyyzzxzJ.     ",
      "    .wwxxyyzzw.      ","     .wwxxyzw.       ","      .wwxyw.        ","       .wwz.         ",
      "        .w.          ",
    ]],
  },
];
